### ISSUE TITLE
Cannot use tags with memcached

### ISSUE THREAD

**Issue by krazyjakee** [MomsFriendlyDevCo/express-middleware-cache#3]
Without tags, the memcached module works perfectly.

With tags, depending on the method the tag is set, we get different errors. For example...

```javascript
expressRouter.get('/:slug', cache('12h', { tag: req => req.params.slug }), async (req, res) => ...
```
Throws
```shell
  cache Using module memcached +0ms
  cache Get d30293ddde6ee1cb98035013742ba3b7ca52584b6cf3be6816235d659a7fe971 +1s
  cache Get emc-tagstore-function tag(req) {
      return req.params.slug;
    } +418ms

node_modules/@momsfriendlydevco/cache/modules/memcached.js:43
			if (err) return cb(err);
                   ^
TypeError: Cannot read property 'push' of undefined
    at node_modules/@MomsFriendlyDevCo/express-middleware-cache/index.js:70:1
```

Using a string...
```javascript
expressRouter.get('/:slug', cache('12h', { tag: 'test' }), async (req, res) => ...
```

Throws
```shell
cache Get d30293ddde6ee1cb98035013742ba3b7ca52584b6cf3be6816235d659a7fe971 +1s
cache Get emc-tagstore-test +445ms
cache Set emc-tagstore-test +1ms

node_modules/@MomsFriendlyDevCo/express-middleware-cache/index.js:104
								throw new Error(err);
^
Error: bad command line format
    at Object.<anonymous> node_modules/@MomsFriendlyDevCo/express-middleware-cache/index.js:104:1)
```

**Comment by hash-bang** [comment]
I'm honestly having difficulty reproducing this one.

Could the issues be related to your memcache config in some way?

The test file has a similar setup to what you're running above and seems to operate with no issues on a Linux machine. What setup are you using?

**Comment by krazyjakee** [comment]
I believe the fix here helped: https://github.com/MomsFriendlyDevCo/express-middleware-cache/issues/1 as I no longer see this issue, sorry
